### ISSUE TITLE
error in isFibonacci.java

### ISSUE THREAD

**Issue by Keerthivardhan1** [aarushi09/Java-Competitive-Programming#11]
error is 
java: class isFibonacci is public, should be declared in a file named isFibonacci.java

**Comment by Keerthivardhan1** [comment]
<img width="244" alt="issue" src="https://user-images.githubusercontent.com/110013820/197516015-3c513976-98b3-42c6-a898-3c08177e8d74.png">

it can be resolved by dumping the code to one  separate class rather then creating two  isFibonacci.java and is-Fibonacci

**Comment by Keerthivardhan1** [comment]
can I do it

**Comment by aarushi09** [comment]
This is for beginners only, the code contributors are writing here is for the first time in java. I understand it is a better practice to have it in separate folders but the main target of this repository is to have multiple solutions to coding problems only. And if you add folders then it'd require changes in the CONTRIBUTING.md file as well, to guide future contributors, this is not currently required. I'll be posting some more issues, you can work on them instead.

**Comment by Keerthivardhan1** [comment]
ok

**Comment by asmi55** [comment]
You know what, @Keerthivardhan1 you can work on this, go ahead, pull in the latest changes and make the desired changes. Also make the corresponding changes to the CONTRIBUTING.md file to guide people on how to contribute.
