### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by aarushi09** [aarushi09/Java-Competitive-Programming#17]
Write a program to enter `n` number of integers to an array and sort the entire array in ascending order using Bubble Sort. 

Here's an example: 
```
Bubble Sort
Enter the number of elements : 
5
Enter the Elements of the array : 
2
0
6
8
1
The sorted array  : 
0 
1 
2 
6 
8
```

**Comment by Arcturus22** [comment]
@aarushi09 
Do we have to write in a particular language?

**Comment by aarushi09** [comment]
Please read the [readme.md](https://github.com/aarushi09/Java-Competitive-Programming/blob/main/README.md) of the repository.
