### ISSUE TITLE
Write a code to check whether the number inputted by user is a Fibonacci number or not?

### ISSUE THREAD

**Issue by aarushi09** [aarushi09/Java-Competitive-Programming#2]
In fibonacci series, next number is the sum of previous two numbers for example 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 etc. The first two numbers of fibonacci series are 0 and 1.

Therefore check whether the number inputted by the user is a Fibonacci number or not.

**Comment by Shreyas-R-7925** [comment]
hello @aarushi09 i want to contribute to this repo 
Please assign it to me

**Comment by aarushi09** [comment]
This issue is open to all, and would be closed on a first serve basis, therefore if you're interested in contributing please make a PR before anyone else does.
