### ISSUE TITLE
Write a program in Java to reverse a number?

### ISSUE THREAD

**Issue by aarushi09** [aarushi09/Java-Competitive-Programming#6]
There are caveats to this problem, you cannot accept a number as a string, you will be needing to accept a number as an integer and then using some logic you need to reverse the program in order to meet the requirements of this issue.

Therefore if your input is `51534` then your output should be `43515`.

**Comment by isaacmtp** [comment]
can you please assign this to me

**Comment by Keerthivardhan1** [comment]
can I work on this

**Comment by aarushi09** [comment]
This issue is open to all, and would be closed on a first serve basis, therefore if you're interested in contributing please make a PR before anyone else does.
